### ISSUE TITLE
Adapter doesn't let process close.

### ISSUE THREAD

**Issue by the-dr-lazy** [jaredwray/keyv-redis#12] opened 2018-02-02 21:04 UTC
Hello

it seems Redis client should explicitly quit.

is there any plan on this subject?

**Comment by lukechilds** [comment] 2018-02-05 07:39
Hi, thanks for reporting, are you able to provide a code example demonstrating your issue?

**Comment by brodmann** [comment] 2018-02-05 10:21
just code example in the documentation:

```
const keyv = new Keyv('redis://127.0.0.1:6379');
```

it appears Redis connection should terminate explicitly with `quit` method but the adapter doesn't share quit method.

node: v9.5.0

**Comment by lukechilds** [comment] 2018-02-05 11:44
I see, so the issue is the file:

```js
const Keyv = require('keyv');
const keyv = new Keyv('redis://127.0.0.1:6379');
```

just hangs forever.

This should probably be fixed in Keyv and tested in [lukechilds/keyv-test-suite](https://github.com/lukechilds/keyv-test-suite). It should test that all storage adapters allow the process to exit.

We should do something like this inside Keyv:

```js
process.on('exit', () => {
    this.opts.store.closeConnection && this.opts.store.closeConnection
});
```

**Comment by brodmann** [comment] 2018-02-05 17:37
I think it is not a good idea to allow clients to close connection just when the process wants to exit.

Is not better to present a public method like quit or end or close !?

**Comment by lukechilds** [comment] 2018-02-06 04:05
You're right, that probably does make more sense.

We can just check if the storage adapter exposes the method and call it, otherwise, do nothing.

**Comment by bahmutov** [comment] 2018-04-27 21:15
Or better, yet, if you expose the Redis client `client` one can call [`client.unref()`](https://github.com/NodeRedis/node_redis#clientunref) to allow Node process to terminate without being blocked by the open connection

**Comment by lukechilds** [comment] 2018-04-28 06:47
@bahmutov Thanks for the suggestion, but Keyv shouldn't encourage storage adapter specific behaviour. It should be abstracted in a way that works with all adapters.

**Comment by rarkins** [comment] 2018-09-01 21:11
@lukechilds is there any major technical hurdle to resolving this problem?

**Comment by lukechilds** [comment] 2018-09-04 14:42
@rarkins No, sorry, I've just been extremely busy with paid work.

I'm down to part-time as of this week so now working through a 7-month backlog of OSS issues 😅. Sorry for the delay, Keyv is a priority for me now.

**Comment by brodmann** [comment] 2018-09-04 21:38
I have free time to work on it for now, can I help?

**Comment by bahmutov** [comment] 2018-09-05 12:48
Would be great solution

**Comment by brodmann** [comment] 2018-09-06 04:46
@lukechilds I think the `close` method of Keyv should support both` end` and `quite` methods of the Redis and also if other adapters have similar methods.
Sometimes (e.g. as a server) we just want to close the connection without thinking about exit signals, also sometimes (e.g. as a worker process) we listen to the exit signals thinking about closing connections.
So I think it has a force parameter for `close` method. when the force is true we expect `end` like action and when force is false the expected behavior is` quite`.

**Comment by lukechilds** [comment] 2018-09-07 15:29
@brodmann that's a nice idea.

Although I think we need to check if we can reliably do this on all storage adapters first. If not we need to decide if we either:

- Add support for both methods in Keyv (via a force arg) and just use the other when one isn't available in a storage adapter.
- Only support what we can support with all storage adapters, whether that's force close or soft close.

The reason for this is because it's a pretty strong selling point of Keyv that storage adapters should be drop-in replacements. I've sacrificed lots of easy performance and convenience wins to keep this true. Having something like `keyv.close(true)` force close with certain adapters but soft close with others would break that mantra.

If we ended up only falling back to a single default like soft close. You could still force close Redis by exposing the storage adapter's native client with something like `keyv.opts.store.client.quit()`.

I know that's ugly but it means people can explicitly opt-in to storage adapter specific behaviour if they need to. However if people do this they should expect their code to break when changing to a different storage adapter.

**Comment by jaredwray** [comment] 2021-11-12 23:09
Closing this issue as we are planning on adding "close" or "disconnect" via Keyv with supported adapters.

**Closed by jaredwray** 2021-11-12 23:09 UTC
